### ISSUE TITLE
ep_mathjax breaks html import

### ISSUE THREAD

**Issue by Athemis** [JohnMcLear/ep_mathjax#3]
With ep_mathjax installed, I recieve the following error while importing a html file. The html was exported from another pad:
```
[2015-03-16 16:56:33.132] [WARN] ImportHtml - HTML was not properly formed [TypeError: Cannot read property 'indexOf' of undefined]
TypeError: Cannot read property 'indexOf' of undefined
    at Object.collectContentPre [as hook_fn] (/usr/share/webapps/etherpad-lite/node_modules/ep_mathjax/static/js/shared.js:8:21)
    at normalizedhook (/usr/share/webapps/etherpad-lite/src/static/js/pluginfw/hooks.js:15:27)
    at hookCallWrapper (/usr/share/webapps/etherpad-lite/src/static/js/pluginfw/hooks.js:21:14)
    at /usr/share/webapps/etherpad-lite/src/static/js/pluginfw/hooks.js:76:14
    at Array.map (native)
    at Function._.map._.collect (/usr/share/webapps/etherpad-lite/src/node_modules/underscore/underscore.js:98:56)
    at Object.exports.callAll (/usr/share/webapps/etherpad-lite/src/static/js/pluginfw/hooks.js:75:24)
    at Object.cc.collectContent (/usr/share/webapps/etherpad-lite/src/static/js/contentcollector.js:514:17)
    at Object.setPadHTML (/usr/share/webapps/etherpad-lite/src/node/utils/ImportHtml.js:40:8)
    at async.series.fileExists (/usr/share/webapps/etherpad-lite/src/node/handler/ImportHandler.js:235:22)
[2015-03-16 16:56:33.138] [WARN] ImportHandler - Error importing, possibly caused by malformed HTML
```
If I uninstall ep_mathjax, I don't get the above mentioned error and the file is imported just fine.

**Comment by JohnMcLear** [comment]
Confirmed, backend tests fail too, will fix.

**Comment by JohnMcLear** [comment]
Fixed, thanks :)
